# Generated by Django 5.2.8 on 2026-06-16 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
