# Generated by Django 6.0.1 on 2026-01-14 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL)),
                ('gym_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_plans', to='gym_branches.gymbranch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_tasks', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['gym_branch', 'created_at'], name='workouts_wo_gym_bra_25ae74_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['created_by', 'created_at'], name='workouts_wo_created_74ecaa_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['member', 'status'], name='workouts_wo_member__a92982_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttask',
            index=models.Index(fields=['workout_plan', 'created_at'], name='workouts_wo_workout_8d0f27_idx'),
        ),
    ]
