# Generated by Django 5.2.8 on 2026-06-28 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutplan_is_active_alter_workoutplan_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workouttask',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
