# Generated by Django 5.2.8 on 2026-06-04 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_branches', '0002_gymbranch_capacity_gymbranch_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('gym_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='gym_branches.gymbranch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in'],
                'indexes': [models.Index(fields=['member', 'check_in'], name='attendance__member__e1d6bc_idx'), models.Index(fields=['gym_branch', 'check_in'], name='attendance__gym_bra_23db73_idx')],
            },
        ),
    ]
